### ISSUE TITLE
Worker processed died w/ rapid memory consumption

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#342]
> This issue was first discovered in Codecov production services 1/22/2017

The worker processes fail unexpectedly and do not properly exit and release memory.

```
Traceback (most recent call last):
  File "/codecov.io/celery/app/trace.py", line 240, in trace_task
  File "/codecov.io/celery/app/trace.py", line 438, in __protected_call__
  File "/codecov.io/app/tasks/task.py", line 386, in run
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 452, in run_sync
  File "/usr/lib/python2.7/site-packages/tornado/ioloop.py", line 752, in start
RuntimeError: IOLoop is already running
```

Current culprits are:

1. Massive reports that consume extreme levels of memory
2. Our GitLab api request for pull commits used pagination and never stopped looping for commits. **Resolved in `v4.3.0`**
3. Massive `git diff` when comparing a single commit or a pull request

**Comment by stevepeak** [comment]
This occurs when processing XML documents that are over 75mb in size.

**Comment by stevepeak** [comment]
See #362
