### ISSUE TITLE
codecov fails on Python 3.2 on Travis CI with error in pyopenssl

### ISSUE THREAD

**Issue by bitranox** [codecov/support#457]
what : python 3.2 / Travic CI
All other Python Versions work correctly. (2.6 .... 3.6)
ONLY on Python 3.2 following Error occurs : 

=== LOG ===

$ codecov
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.6/bin/codecov", line 7, in <module>
    from codecov import main
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/codecov/__init__.py", line 7, in <module>
    import requests
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/urllib3/contrib/pyopenssl.py", line 169
    for prefix in [u'*.', u'.']:
                       ^
SyntaxError: invalid syntax

=== /LOG ===

**Comment by jayvdb** [comment]
G'day, this bug report belongs over at https://github.com/codecov/codecov-python .  Do you want to re-create there, for attribution?
Or ignore, and I'll copy it across.
